services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - discord-bot-network
    depends_on:
      - sqlite

  sqlite:
    container_name: sqlite
    image: sqlite
    environment:
      - SQLUTE_USER=user
      - SQLUTE_PASSWORD=password
      - SQLUTE_DATABASE=database
    networks:
      - discord-bot-network
    volumes:
      - sqlite-data:/var/lib/sqlite


networks:
  discord-bot-network:
    driver: bridge

volumes:
  node_modules:
  sqlite-data:
